version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - JWT_SECRET="SECRET"
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RARBBITMQ_PASSWORD=guest
      - DB_USERNAME=root
      - DB_PASSWORD=popo1212
      - DB_PORT=3306
      - DB_HOST=host.docker.internal
      - DB_NAME=auth_rest
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  redis_data:
  rabbitmq_data:
